import { makeTrack } from "./estimator.js";
import type { Track } from "./types.js";

const RAW_PLAYLIST: Array<[string, string]> = [
  ["IM NOT GOD BUT I WISH I WAS", "smokedope2016"],
  ["Pierwsze Koncerty", "Monday Waxie"],
  ["BACKROOMS", "Playboi Carti & Travis Scott"],
  ["antysemita", "witchkilluh"],
  ["BOMB", "¥$, North West & Chicago West"],
  ["2024", "Playboi Carti"],
  ["Thanks", "Joeyy"],
  ["B.O.R. (Birth of Rap)", "Soulja Boy Tell 'Em & Lil B"],
  ["Japonia (REMIX)", "CBW, Mlody Korden, Cygan9 & 33ROBOT"],
  ["SICKO MODE", "Travis Scott"],
  ["Lean 4 Real (feat. Skepta)", "Playboi Carti"],
  ["Runaway (feat. Pusha T)", "Kanye West"],
  ["myśli pułapki", "Rusina, Lister & Bully"],
  ["J. Laskowski 2Pac Baby Dont Cry", "J. Laskowski"],
  ["Wwa Na Kxxksie (feat. tosiek)", "Yung Adisz, schafter & Gottastral"],
  ["In the Air", "Destroy Lonely"],
  ["Pop", "OsamaSon"],
  ["No More Parties in LA", "Kanye West"],
  ["Wolves", "Kanye West"],
  ["Saint Pablo", "Kanye West"],
  ["QUEST", "reeb"],
  ["Closed Eyes (Def Jam World Tour)", "Rusina, OG Eastbull & Def Jam World Tour"],
  ["Feedback", "Kanye West"],
  ["MUNYUN", "Playboi Carti"],
  ["Coat I Would Buy", "Joeyy"],
  ["TALKING", "¥$, Kanye West & Ty Dolla $ign"],
  ["Byłem W Psychiatryku", "Yung Adisz, Ozzy Baby & Okekel"],
  ["Nienawidze Lata", "Mlody Korden"],
  ["Jakby Mogla Zabic1017", "Mlody Korden"],
  ["ANGELA", "Mlody Korden"],
  ["BlaBla", "Mlody Korden, Cygan9 & Directed by Kooza"],
  ["Miami", "Mlody Korden, Worek & SB Maffija"],
  ["Goyard Torba", "Mlody Korden, Swizzy & pieruun"],
  ["Ice Spice", "Mlody Korden & Rotel Beatz"],
  ["BUFFALO", "Drabusheyka"],
  ["slajm na bagu", "Mlody Korden"],
  ["margiela margiela 2", "Mlody Korden"],
  ["Nowy Worek", "Cygan9, młody dymas & YEEGOR"],
  ["Barbie (Remix)", "Haranczykov, Cygan9 & MSF"],
  ["stay humble", "9ssey, Cygan9 & Kersie"],
  ["Bloody Nose", "9ssey"],
  ["Swag99", "Cygan9 & młody dymas"],
  ["Lody Genzie", "Cygan9, młodszygibig & Haranczykov"],
  ["BABY LOLA (ceskie divki)", "spazma"],
  ["DODO", "Kamil"],
  ["NA ROGU", "Rusina, Lister & Learnhowtohustle"],
  ["Muskrat (feat. Marlon DuBois)", "Joeyy"],
  ["BEIJING BOBO", "spazma"],
  ["UNDERARMOUR", "Amar, maharadzza, Eddie Block, RICHIE & Adash"],
  ["TERAZ WIEM FREESTYLE", "wane"],
  ["UNDERWAY CYPHER", "UnderwayPL, luokhan, AG, Vorzu & GeezyBeatz"],
  ["Na Haju", "LHTH"],
  ["zachod slonca", "Mlody Korden"],
  ["DOPE", "spazma & izonya polska"],
  ["CHUJ W TO", "spazma"],
  ["Wielkodupna Darianna", "spazma"],
  ["Mini Man", "Okekel & Champion"],
  ["KŁO PO TY", "Kamil, ciaglamantra & atraxy"],
  ["SILESIAN CYPHER", "Okekel, Vkie, Aleshen & Miszel"],
  ["Consequence (Def Jam World Tour)", "Rusina & Def Jam World Tour"],
  ["Zapłakane matki (Def Jam World Tour)", "Yung Adisz, Rusina & Def Jam World Tour"],
  ["DZIECIAKI to ROBIĄ", "Kidzlori, Okekel & Champion"],
  ["Zwolnij?", "Okekel, Champion & Deemz"],
  ["Wszystkim Czym Chcesz", "wane"],
  ["PO TAŃCU", "Drabusheyka & Mlody West"],
  ["Co jest?!", "Mlody West & Drabusheyka"],
  ["KOE-L SKYE", "wane"],
  ["Już nie mogę przegrać", "Aleshen, Mlody West & BAHsick"],
  ["co to znaczy", "Kidzlori & Skibovicz"],
  ["VULTURES", "¥$, Kanye West & Ty Dolla $ign"],
  ["Kiri Guap", "Mlody Korden"],
  ["You & Me (feat. Eliza Doolittle)", "Disclosure"],
  ["4 RANO", "Rusina"],
  ["Po Co?", "wane"],
  ["No morë talk", "Yeat"],
  ["unemployed anthem", "maharadzza, Eddie Block & Adash"],
  ["hebe", "maharadzza & 1olliee"],
  ["NA FORACH", "Rusina & Young Igi"],
  ["MOONDANCE", "Drabusheyka & schafter"],
  ["SEN", "javier & gogetmxney"],
  ["pierwsze molly to jak sen", "LuKs & Kersie"],
  ["CHCIAŁBYM BYĆ", "LHTH & Sheder"],
  ["Pudełka", "Karus, javier & prod. adi"],
  ["TU I TERAZZ", "Drabusheyka & Żabson"],
  ["JA = TY", "Drabusheyka & Gmeniu"],
  ["W PRIME", "Drabusheyka"],
  ["Break It Off", "PinkPantheress"],
  ["trzeźwym być", "Rusina, Learnhowtohustle & nofuk"],
  ["nowy $wag", "Rusina, LHTH & Learnhowtohustle"],
  ["LABUBU", "javier & Kamil"],
  ["Błoto", "wane"],
  ["Victory Lap Five", "Fred again.., Skepta, PlaqueBoyMax & Denzel Curry"],
  ["Alaa pt.1", "Kamil"],
  ["Monday Madness", "Monday Waxie"],
  ["DANCE FOR ME", "Kamil"],
  ["CHODZ ZE MNA NA GORE", "Drabusheyka"],
  ["PERSZING", "LHTH"],
  ["Splendor", "wane"],
  ["All Mine", "Kanye West"],
  ["AGAIN AND AGAIN", "GABSON SAN"],
  ["WIEM DOBRZE", "Rusina & SHEDER"],
  ["NARNIA", "Kamil & Narri"],
  ["Esskeetit", "Lil Pump"],
  ["Members Only Cypher", "Rusina, Yung Adisz & Asster"],
  ["Żale", "Okekel"],
  ["50 koła", "Okekel, Mlody West & Nolyrics Beats"],
  ["Kocham Cię", "Okekel"],
  ["Ain't No Shit", "37Nestee, Ørzeł & 37 in this b!tch"],
  ["eskeemos", "schafter"],
  ["ZEMSTA", "Rusina, WHITE WIDOW & Vkie"],
  ["po paru", "podziemie fan"],
  ["ZEBY ROZGRZAC WROCLAW", "mlodykamil fan"],
  ["SEKTOR | SPICY MIC Performance", "Gryzzly & Myczu"],
  ["Martin Shkreli Freestyle", "schafter"],
  ["Szara prawda", "Okekel & Bonus RPK"],
  ["TRYB SPORTOWY", "javier & gogetmxney"],
  ["DEAD", "¥$, Future & Lil Durk"],
  ["GO!", "Rusina"],
  ["ily denim", "Denim Street"],
  ["DM", "Hubert."],
  ["XXL", "Trill Pem, Bully & Jezzy C."],
  ["KUCHARZOWA", "Mlody Korden"],
  ["tańce", "Hubert."],
  ["Warszawski sen", "Mlody West"],
  ["YEAH!!! (feat. javier)", "prod. adi, Karus & Kamil"],
  ["g.i joe", "podziemie fan"],
  ["Mhm Mhm", "Kidzlori"],
  ["girl", "2hollis"],
  ["veteran", "podziemie fan"],
  ["Jestem W Stanie", "Vkie & Pazzy"],
  ["LEAK", "Aleshen, Kamil & Macias"],
  ["KULT", "Mlody West & Okekel"],
  ["Jurij Gagarin", "Okekel"],
  ["MVP", "Okekel"],
  ["Kodak", "Okekel"],
  ["Bez pokoju", "Okekel"],
  ["Rodo", "Rusina & Learnhowtohustle"],
  ["Bez Zmian", "Aleshen"],
  ["KLEOPATRA", "Kidzlori"],
  ["SALSA", "javier"],
  ["JAKOŚ JESTEM", "Rusina"],
  ["nina", "ColdIone"],
  ["cartier", "Rusina & Learnhowtohustle"],
  ["DOBRZE ZNAM SIĘ Z WITAMINĄ", "hugevkie"],
  ["PYSK", "javier & gogetmxney"],
  ["Zejść", "wane"],
  ["Gniazdo Freestyle", "37Nestee, Ørzeł & 37 in this b!tch"],
  ["On My Mind", "37Nestee, Ørzeł & 37 in this b!tch"],
  ["BIORE TO CO MOJE", "G8KEEP VAULT"],
  ["Truskulowy 2", "Vkie"],
  ["hcwd2", "Lemik Golemik"],
  ["Lookin (feat. Lil Uzi Vert)", "Playboi Carti"],
  ["CRUSH", "Playboi Carti & Travis Scott"],
  ["MOJO JOJO", "Playboi Carti"],
  ["SOMBRERO", "LHTH, Stachu & Learnhowtohustle"],
  ["MAM STYL", "brokos"],
  ["Rolling Stones", "37 in this b!tch, 37Nestee & sz ymeh"],
  ["bitch face", "Monday Waxie"],
  ["Szał", "Vkie"],
  ["LAST BREATH", "Ye"],
  ["LOSING YOUR MIND", "Ye"],
  ["365", "Kidzlori"],
  ["OCEAN SPRAY", "Kidzlori"],
  ["B2B", "Kidzlori"],
  ["KING", "Kanye West"],
  ["4X4", "Travis Scott"],
  ["twój plugg 2", "Mlody Korden & Ozzy Baby"],
  ["GDZIE JEST RUSINA", "G8KEEP VAULT"],
  ["FRED PERRY", "Macias, WHITE WIDOW & RC"],
  ["Luty", "Otsochodzi"],
  ["Maison Margiela", "slowez"],
  ["Rundki", "Malik Montana"],
  ["Plain Jane", "Malik Montana"],
  ["Bez Listy", "Malik Montana & TYK"],
  ["EFEKT KULI ŚNIEŻNEJ", "Bonus RPK & Vkie"]
];

export const seedPlaylistTracks: Track[] = RAW_PLAYLIST.map(([title, artist]) => makeTrack(title, artist));

export function mergeTracks(primary: Track[], incoming: Track[]) {
  const map = new Map<string, Track>();
  for (const track of [...primary, ...incoming]) {
    const key = `${track.title.toLowerCase()}::${track.artist.toLowerCase()}`;
    const previous = map.get(key);
    if (!previous || previous.confidence < track.confidence) map.set(key, track);
  }
  return [...map.values()];
}
